dataset = {
        "Football players": [
            "MO SALAH",
            "LIONEL MESSI",
            "KEVIN DE BRUYNE",
            "CRISTIANO RONALDO",
            "NGOLO KANTE",
            "KYLIAN MBAPPE",
            "NEYMAR",
            "KARIM BENZEMA", 
            "DANI ALVES",
            "ZLATAN IBRAHIMOVIC",
        ],
        "Rockstars": [
            "LIAM GALLAGHER",
            "AXEL ROSE",
            "ERIC CLAPTON",
            "SLASH",
            "PAUL MCCARTNEY",
            "MICK JAGGER",
            "OZZY OSBOURNE",
            "JIMI HENDRIX",
            "BRUCE SPRINGSTEEN",
            "JOHN LENNON",
            "DAVID BOWIE",
        ],
        "Marvel Characters": [
            "CAPTAIN AMERICA",
            "IRON MAN",
            "THANOS",
            "HAWKEYE",
            "BLACK PANTHER",
            "BLACK WIDOW",
            "SPIDERMAN",
            "STARLORD",
            "THOR",
            "DOCTOR STRANGE",
        ],
    }